apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vijay-app-ui
  name: vijay-app-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vijay-app-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vijay-app-ui
    spec:
      containers:
      - image: pemanjun/vijay-ui-app:appv3
        name: vijay-ui-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
[vijay@ip-172-31-16-246 vijay-cisco-webUI]$ kubectl create  service loadbalancer  vijay-lb001  --tcp 80:80 --dry-run=client -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vijay-lb001
  name: vijay-lb001
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vijay-app-ui
  type: LoadBalancer
status:
  loadBalancer: {}
